<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Jeremy Dawkins" />

<meta name="date" content="2021-10-21" />

<title>Case Study 01 EDA Beers_Breweries</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<script src="site_libs/plotly-binding-4.9.4.1/plotly.js"></script>
<script src="site_libs/typedarray-0.1/typedarray.min.js"></script>
<link href="site_libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="site_libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>
<link href="site_libs/plotly-htmlwidgets-css-1.57.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="site_libs/plotly-main-1.57.1/plotly-latest.min.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">My Website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="Case-Study-01.html">Beer Study/Case Study 1</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Case Study 01 EDA Beers_Breweries</h1>
<h4 class="author">Jeremy Dawkins</h4>
<h4 class="date">10/21/2021</h4>

</div>


<p>#Hello, The purpose of this code is to explain what possible ways as a company for Budweiser can improve business in certain regional regions and/or possible provide new goods and services where the market is has untapped potential.</p>
<p>#I am hoping my code below can answer some of your questions on how this data allowed us to make an informed decision on what’s the next big source of revenue.</p>
<p>#Load Library that will be in use for this project</p>
<p>#We want to read in our data set from the beers.csv and the breweries.csv</p>
<pre><code>##                  Name Beer_ID   ABV IBU Brewery_id
## 1            Pub Beer    1436 0.050  NA        409
## 2         Devil&#39;s Cup    2265 0.066  NA        178
## 3 Rise of the Phoenix    2264 0.071  NA        178
## 4            Sinister    2263 0.090  NA        178
## 5       Sex and Candy    2262 0.075  NA        178
##                            Style Ounces
## 1            American Pale Lager     12
## 2        American Pale Ale (APA)     12
## 3                   American IPA     12
## 4 American Double / Imperial IPA     12
## 5                   American IPA     12</code></pre>
<pre><code>##   Brew_ID                      Name          City State
## 1       1        NorthGate Brewing    Minneapolis    MN
## 2       2 Against the Grain Brewery    Louisville    KY
## 3       3  Jack&#39;s Abby Craft Lagers    Framingham    MA
## 4       4 Mike Hess Brewing Company     San Diego    CA
## 5       5   Fort Point Beer Company San Francisco    CA</code></pre>
<pre><code>## &#39;data.frame&#39;:    2410 obs. of  7 variables:
##  $ Name      : Factor w/ 2305 levels &quot;#001 Golden Amber Lager&quot;,..: 1638 577 1705 1842 1819 268 1160 758 1093 486 ...
##  $ Beer_ID   : int  1436 2265 2264 2263 2262 2261 2260 2259 2258 2131 ...
##  $ ABV       : num  0.05 0.066 0.071 0.09 0.075 0.077 0.045 0.065 0.055 0.086 ...
##  $ IBU       : int  NA NA NA NA NA NA NA NA NA NA ...
##  $ Brewery_id: int  409 178 178 178 178 178 178 178 178 178 ...
##  $ Style     : Factor w/ 100 levels &quot;&quot;,&quot;Abbey Single Ale&quot;,..: 19 18 16 12 16 80 18 22 18 12 ...
##  $ Ounces    : num  12 12 12 12 12 12 12 12 12 12 ...</code></pre>
<pre><code>## &#39;data.frame&#39;:    558 obs. of  4 variables:
##  $ Brew_ID: int  1 2 3 4 5 6 7 8 9 10 ...
##  $ Name   : chr  &quot;NorthGate Brewing &quot; &quot;Against the Grain Brewery&quot; &quot;Jack&#39;s Abby Craft Lagers&quot; &quot;Mike Hess Brewing Company&quot; ...
##  $ City   : chr  &quot;Minneapolis&quot; &quot;Louisville&quot; &quot;Framingham&quot; &quot;San Diego&quot; ...
##  $ State  : chr  &quot; MN&quot; &quot; KY&quot; &quot; MA&quot; &quot; CA&quot; ...</code></pre>
<pre><code>##                      Name         Beer_ID            ABV         
##  Nonstop Hef Hop       :  12   Min.   :   1.0   Min.   :0.00100  
##  Dale&#39;s Pale Ale       :   6   1st Qu.: 808.2   1st Qu.:0.05000  
##  Oktoberfest           :   6   Median :1453.5   Median :0.05600  
##  Longboard Island Lager:   4   Mean   :1431.1   Mean   :0.05977  
##  1327 Pod&#39;s ESB        :   3   3rd Qu.:2075.8   3rd Qu.:0.06700  
##  Boston Lager          :   3   Max.   :2692.0   Max.   :0.12800  
##  (Other)               :2376                    NA&#39;s   :62       
##       IBU           Brewery_id                               Style     
##  Min.   :  4.00   Min.   :  1.0   American IPA                  : 424  
##  1st Qu.: 21.00   1st Qu.: 94.0   American Pale Ale (APA)       : 245  
##  Median : 35.00   Median :206.0   American Amber / Red Ale      : 133  
##  Mean   : 42.71   Mean   :232.7   American Blonde Ale           : 108  
##  3rd Qu.: 64.00   3rd Qu.:367.0   American Double / Imperial IPA: 105  
##  Max.   :138.00   Max.   :558.0   American Pale Wheat Ale       :  97  
##  NA&#39;s   :1005                     (Other)                       :1298  
##      Ounces     
##  Min.   : 8.40  
##  1st Qu.:12.00  
##  Median :12.00  
##  Mean   :13.59  
##  3rd Qu.:16.00  
##  Max.   :32.00  
## </code></pre>
<pre><code>##     Brew_ID          Name               City              State          
##  Min.   :  1.0   Length:558         Length:558         Length:558        
##  1st Qu.:140.2   Class :character   Class :character   Class :character  
##  Median :279.5   Mode  :character   Mode  :character   Mode  :character  
##  Mean   :279.5                                                           
##  3rd Qu.:418.8                                                           
##  Max.   :558.0</code></pre>
<p>#Renaming the column names for each data set to make them more readable</p>
<pre><code>## [1] &quot;Brewery_ID&quot;   &quot;Brewery_Name&quot; &quot;City&quot;         &quot;State&quot;</code></pre>
<pre><code>## [1] &quot;Beer_Name&quot;         &quot;Beer_ID&quot;           &quot;Alcohol_by_Volume&quot;
## [4] &quot;Bitterness_Units&quot;  &quot;Brewery_ID&quot;        &quot;Beer_Style&quot;       
## [7] &quot;Ounces&quot;</code></pre>
<p>#Question 1: How many Breweries are present in each state?</p>
<p>#We created a bar chart to display how many breweries are in each state as well as a list and table #The states with the highest brewery count is: Colorado, California, Michigan, Oregon and Texas.. This would be a great market to start if any new releases of beer Budweiser wants to create.</p>
<pre><code>## 
##  AK  AL  AR  AZ  CA  CO  CT  DC  DE  FL  GA  HI  IA  ID  IL  IN  KS  KY  LA  MA 
##   7   3   2  11  39  47   8   1   2  15   7   4   5   5  18  22   3   4   5  23 
##  MD  ME  MI  MN  MO  MS  MT  NC  ND  NE  NH  NJ  NM  NV  NY  OH  OK  OR  PA  RI 
##   7   9  32  12   9   2   9  19   1   5   3   3   4   2  16  15   6  29  25   5 
##  SC  SD  TN  TX  UT  VA  VT  WA  WI  WV  WY 
##   4   1   3  28   4  16  10  23  20   1   4</code></pre>
<pre><code>## # A tibble: 51 x 2
##    State     n
##    &lt;chr&gt; &lt;int&gt;
##  1 &quot; AK&quot;     7
##  2 &quot; AL&quot;     3
##  3 &quot; AR&quot;     2
##  4 &quot; AZ&quot;    11
##  5 &quot; CA&quot;    39
##  6 &quot; CO&quot;    47
##  7 &quot; CT&quot;     8
##  8 &quot; DC&quot;     1
##  9 &quot; DE&quot;     2
## 10 &quot; FL&quot;    15
## # ... with 41 more rows</code></pre>
<p><img src="Case-Study-01_files/figure-html/breweries%20per%20state-1.png" width="672" /></p>
<p>#Question 2: Merge the Beer and Breweries data set. Print the first 6 observations and the last 6 observations to check the merged file.</p>
<p>#We were able to merge both data sets together and printing the first 6 obserations and the last 6 observations which is shown.</p>
<pre><code>##   Brewery_ID     Beer_Name Beer_ID Alcohol_by_Volume Bitterness_Units
## 1          1  Get Together    2692             0.045               50
## 2          1 Maggie&#39;s Leap    2691             0.049               26
## 3          1    Wall&#39;s End    2690             0.048               19
## 4          1       Pumpion    2689             0.060               38
## 5          1    Stronghold    2688             0.060               25
## 6          1   Parapet ESB    2687             0.056               47
##                            Beer_Style Ounces       Brewery_Name        City
## 1                        American IPA     16 NorthGate Brewing  Minneapolis
## 2                  Milk / Sweet Stout     16 NorthGate Brewing  Minneapolis
## 3                   English Brown Ale     16 NorthGate Brewing  Minneapolis
## 4                         Pumpkin Ale     16 NorthGate Brewing  Minneapolis
## 5                     American Porter     16 NorthGate Brewing  Minneapolis
## 6 Extra Special / Strong Bitter (ESB)     16 NorthGate Brewing  Minneapolis
##   State
## 1    MN
## 2    MN
## 3    MN
## 4    MN
## 5    MN
## 6    MN</code></pre>
<pre><code>##      Brewery_ID                 Beer_Name Beer_ID Alcohol_by_Volume
## 2405        556             Pilsner Ukiah      98             0.055
## 2406        557  Heinnieweisse Weissebier      52             0.049
## 2407        557           Snapperhead IPA      51             0.068
## 2408        557         Moo Thunder Stout      50             0.049
## 2409        557         Porkslap Pale Ale      49             0.043
## 2410        558 Urban Wilderness Pale Ale      30             0.049
##      Bitterness_Units              Beer_Style Ounces
## 2405               NA         German Pilsener     12
## 2406               NA              Hefeweizen     12
## 2407               NA            American IPA     12
## 2408               NA      Milk / Sweet Stout     12
## 2409               NA American Pale Ale (APA)     12
## 2410               NA        English Pale Ale     12
##                       Brewery_Name          City State
## 2405         Ukiah Brewing Company         Ukiah    CA
## 2406       Butternuts Beer and Ale Garrattsville    NY
## 2407       Butternuts Beer and Ale Garrattsville    NY
## 2408       Butternuts Beer and Ale Garrattsville    NY
## 2409       Butternuts Beer and Ale Garrattsville    NY
## 2410 Sleeping Lady Brewing Company     Anchorage    AK</code></pre>
<p>#Question 3: Address the Missing values in each column. #We decided to address the missing value and NA’s in data frame by taking the median of the available ABV and IBU and used that number to replace the missing data.</p>
<pre><code>## &#39;data.frame&#39;:    2410 obs. of  10 variables:
##  $ Brewery_ID       : int  1 1 1 1 1 1 2 2 2 2 ...
##  $ Beer_Name        : Factor w/ 2305 levels &quot;#001 Golden Amber Lager&quot;,..: 802 1258 2185 1640 1926 1525 458 1218 43 71 ...
##  $ Beer_ID          : int  2692 2691 2690 2689 2688 2687 2686 2685 2684 2683 ...
##  $ Alcohol_by_Volume: num  0.045 0.049 0.048 0.06 0.06 0.056 0.08 0.125 0.077 0.042 ...
##  $ Bitterness_Units : int  50 26 19 38 25 47 68 80 25 42 ...
##  $ Beer_Style       : Factor w/ 100 levels &quot;&quot;,&quot;Abbey Single Ale&quot;,..: 16 77 48 83 22 57 12 46 77 18 ...
##  $ Ounces           : num  16 16 16 16 16 16 16 16 16 16 ...
##  $ Brewery_Name     : chr  &quot;NorthGate Brewing &quot; &quot;NorthGate Brewing &quot; &quot;NorthGate Brewing &quot; &quot;NorthGate Brewing &quot; ...
##  $ City             : chr  &quot;Minneapolis&quot; &quot;Minneapolis&quot; &quot;Minneapolis&quot; &quot;Minneapolis&quot; ...
##  $ State            : chr  &quot; MN&quot; &quot; MN&quot; &quot; MN&quot; &quot; MN&quot; ...</code></pre>
<p>#Question 4: Compute the median alcohol content and international bitterness unit for each state. Plot a bar chart to compare.</p>
<p>#We computed the median ABV and IBU for each state to give an idea on what people to tend to drink in their respective states. Where does Budweiser traditionally fall on this scale? #However, when looking at the median IBU values, there is much more spread between states. What this would suggest is that different states have different views on how bitter their beer should be (IBU level). Traditionally Budweiser falls right in the middle of the ABV range at 5%, but much lower than the median IBU for all states in the dataset (12 IBU)! Therefore, the evidence suggests that craft beer consumers might prefer Budweiser if it were more bitter (greater IBU). <img src="Case-Study-01_files/figure-html/median%20IBU%20and%20ABV-1.png" width="672" /><img src="Case-Study-01_files/figure-html/median%20IBU%20and%20ABV-2.png" width="672" /></p>
<p>#Question 5: Which state has the maximum alcoholic (ABV) beer? Which state has the most bitter (IBU) beer? #It seems the maximum ABV among craft beers is 12.8% (Colorado) which is about 2.5x higher than Budweiser and a maxmimum IBU of 138 (Oregon) which is 11.5x higher than Budweiser.</p>
<pre><code>## # A tibble: 1 x 2
##   State   ABV
##   &lt;chr&gt; &lt;dbl&gt;
## 1 &quot; CO&quot; 0.128</code></pre>
<pre><code>## # A tibble: 1 x 2
##   State   IBU
##   &lt;chr&gt; &lt;dbl&gt;
## 1 &quot; OR&quot;   138</code></pre>
<p>#Question 6: Comment on the summary statistics and distribution of the ABV variable</p>
<p>#We can see that the distribution is slightly right skewed, but the median and mean of the ABV is between 5 and 6%. We know that Budweiser is around 5 perent which is lower than the mean and median. It precisely falls within the 1st quantile range of ABV percentages. We know that Bud light falls with 4.2 percent falls outside the 1st quantile range.</p>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## 0.00100 0.05000 0.05600 0.05972 0.06700 0.12800</code></pre>
<div id="htmlwidget-25e9e1cabf9ba998655f" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-25e9e1cabf9ba998655f">{"x":{"data":[{"orientation":"v","width":[0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670888,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670886,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888,0.160759493670888],"base":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"x":[0.160759493670886,0.321518987341772,0.482278481012658,0.643037974683544,0.80379746835443,0.964556962025317,1.1253164556962,1.28607594936709,1.44683544303797,1.60759493670886,1.76835443037975,1.92911392405063,2.08987341772152,2.25063291139241,2.41139240506329,2.57215189873418,2.73291139240506,2.89367088607595,3.05443037974684,3.21518987341772,3.37594936708861,3.53670886075949,3.69746835443038,3.85822784810127,4.01898734177215,4.17974683544304,4.34050632911392,4.50126582278481,4.6620253164557,4.82278481012658,4.98354430379747,5.14430379746836,5.30506329113924,5.46582278481013,5.62658227848101,5.7873417721519,5.94810126582279,6.10886075949367,6.26962025316456,6.43037974683544,6.59113924050633,6.75189873417722,6.9126582278481,7.07341772151899,7.23417721518987,7.39493670886076,7.55569620253165,7.71645569620253,7.87721518987342,8.03797468354431,8.19873417721519,8.35949367088608,8.52025316455697,8.68101265822785,8.84177215189874,9.00253164556962,9.16329113924051,9.32405063291139,9.48481012658228,9.64556962025317,9.80632911392405,9.96708860759494,10.1278481012658,10.2886075949367,10.4493670886076,10.6101265822785,10.7708860759494,10.9316455696203,11.0924050632911,11.253164556962,11.4139240506329,11.5746835443038,11.7354430379747,11.8962025316456,12.0569620253165,12.2177215189873,12.3784810126582,12.5392405063291,12.7,12.8607594936709],"y":[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,3,1,6,4,21,40,47,28,89,89,134,225,169,60,225,125,69,161,23,99,151,20,79,32,111,55,8,48,14,17,62,22,11,30,12,8,24,16,6,9,10,3,36,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1],"text":["count:   1<br />ABV * 100:  0.1607595","count:   0<br />ABV * 100:  0.3215190","count:   0<br />ABV * 100:  0.4822785","count:   0<br />ABV * 100:  0.6430380","count:   0<br />ABV * 100:  0.8037975","count:   0<br />ABV * 100:  0.9645570","count:   0<br />ABV * 100:  1.1253165","count:   0<br />ABV * 100:  1.2860759","count:   0<br />ABV * 100:  1.4468354","count:   0<br />ABV * 100:  1.6075949","count:   0<br />ABV * 100:  1.7683544","count:   0<br />ABV * 100:  1.9291139","count:   0<br />ABV * 100:  2.0898734","count:   0<br />ABV * 100:  2.2506329","count:   0<br />ABV * 100:  2.4113924","count:   0<br />ABV * 100:  2.5721519","count:   3<br />ABV * 100:  2.7329114","count:   0<br />ABV * 100:  2.8936709","count:   0<br />ABV * 100:  3.0544304","count:   3<br />ABV * 100:  3.2151899","count:   1<br />ABV * 100:  3.3759494","count:   6<br />ABV * 100:  3.5367089","count:   4<br />ABV * 100:  3.6974684","count:  21<br />ABV * 100:  3.8582278","count:  40<br />ABV * 100:  4.0189873","count:  47<br />ABV * 100:  4.1797468","count:  28<br />ABV * 100:  4.3405063","count:  89<br />ABV * 100:  4.5012658","count:  89<br />ABV * 100:  4.6620253","count: 134<br />ABV * 100:  4.8227848","count: 225<br />ABV * 100:  4.9835443","count: 169<br />ABV * 100:  5.1443038","count:  60<br />ABV * 100:  5.3050633","count: 225<br />ABV * 100:  5.4658228","count: 125<br />ABV * 100:  5.6265823","count:  69<br />ABV * 100:  5.7873418","count: 161<br />ABV * 100:  5.9481013","count:  23<br />ABV * 100:  6.1088608","count:  99<br />ABV * 100:  6.2696203","count: 151<br />ABV * 100:  6.4303797","count:  20<br />ABV * 100:  6.5911392","count:  79<br />ABV * 100:  6.7518987","count:  32<br />ABV * 100:  6.9126582","count: 111<br />ABV * 100:  7.0734177","count:  55<br />ABV * 100:  7.2341772","count:   8<br />ABV * 100:  7.3949367","count:  48<br />ABV * 100:  7.5556962","count:  14<br />ABV * 100:  7.7164557","count:  17<br />ABV * 100:  7.8772152","count:  62<br />ABV * 100:  8.0379747","count:  22<br />ABV * 100:  8.1987342","count:  11<br />ABV * 100:  8.3594937","count:  30<br />ABV * 100:  8.5202532","count:  12<br />ABV * 100:  8.6810127","count:   8<br />ABV * 100:  8.8417722","count:  24<br />ABV * 100:  9.0025316","count:  16<br />ABV * 100:  9.1632911","count:   6<br />ABV * 100:  9.3240506","count:   9<br />ABV * 100:  9.4848101","count:  10<br />ABV * 100:  9.6455696","count:   3<br />ABV * 100:  9.8063291","count:  36<br />ABV * 100:  9.9670886","count:   0<br />ABV * 100: 10.1278481","count:   0<br />ABV * 100: 10.2886076","count:   1<br />ABV * 100: 10.4493671","count:   0<br />ABV * 100: 10.6101266","count:   0<br />ABV * 100: 10.7708861","count:   0<br />ABV * 100: 10.9316456","count:   0<br />ABV * 100: 11.0924051","count:   0<br />ABV * 100: 11.2531646","count:   0<br />ABV * 100: 11.4139241","count:   0<br />ABV * 100: 11.5746835","count:   0<br />ABV * 100: 11.7354430","count:   0<br />ABV * 100: 11.8962025","count:   1<br />ABV * 100: 12.0569620","count:   0<br />ABV * 100: 12.2177215","count:   0<br />ABV * 100: 12.3784810","count:   1<br />ABV * 100: 12.5392405","count:   0<br />ABV * 100: 12.7000000","count:   1<br />ABV * 100: 12.8607595"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(89,89,89,1)","line":{"width":1.88976377952756,"color":"transparent"}},"showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":43.7625570776256,"r":7.30593607305936,"b":40.1826484018265,"l":43.1050228310502},"plot_bgcolor":"rgba(235,235,235,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"title":{"text":"Distribution of ABV","font":{"color":"rgba(0,0,0,1)","family":"","size":17.5342465753425},"x":0,"xref":"paper"},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-0.562658227848101,13.5841772151899],"tickmode":"array","ticktext":["0","5","10"],"tickvals":[0,5,10],"categoryorder":"array","categoryarray":["0","5","10"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y","title":{"text":"Percent ABV","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-11.25,236.25],"tickmode":"array","ticktext":["0","50","100","150","200"],"tickvals":[0,50,100,150,200],"categoryorder":"array","categoryarray":["0","50","100","150","200"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x","title":{"text":"count","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":false,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.88976377952756,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.689497716895}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","showSendToCloud":false},"source":"A","attrs":{"3bac259241f7":{"x":{},"type":"bar"}},"cur_data":"3bac259241f7","visdat":{"3bac259241f7":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>#Question 7: Is there an apparent relationship between the bitterness of the beer and its alcoholic content? Draw a scatterplot. Expalin</p>
<p>#We that there is a positive relationship between ABV and IBU from the scatterplot we can see the higher IBU related to higher ABV percentage in the beer and lower IBU has lower ABV. We see that most ABV that falls around 5% similar to Budweiser their IBU is lower than 50 percent.</p>
<pre><code>## Warning: Ignoring unknown parameters: linetpye</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="Case-Study-01_files/figure-html/relationship%20between%20IBU%20and%20ABV-1.png" width="672" /></p>
<pre><code>## 
## Call:
## lm(formula = AllBeerDataFrame$ABV ~ AllBeerDataFrame$IBU, data = AllBeerDataFrame)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.042131 -0.006229 -0.001937  0.003881  0.073755 
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          4.631e-02  4.346e-04  106.56   &lt;2e-16 ***
## AllBeerDataFrame$IBU 3.308e-04  9.218e-06   35.89   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.0108 on 2356 degrees of freedom
##   (52 observations deleted due to missingness)
## Multiple R-squared:  0.3534, Adjusted R-squared:  0.3532 
## F-statistic:  1288 on 1 and 2356 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>#Question 8: Budweiser would also like to investigate the difference with respect to IBU and ABV between IPA’s (India Pale Ales) and other types of Ale</p>
<p>#We see a difference with our KNN classification, with k = 5 that our model seems to predict with a 90% accuracy and a sensitivity of 93% and specificity of 85%. #We also see with K = 10 our accuracy seem to fall a bit with 87.9% and our sensitivity is 91% and specificity is 82%.</p>
<pre><code>## Adding missing grouping variables: `Beer_Style`
## Adding missing grouping variables: `Beer_Style`</code></pre>
<p>#Question 9: Additional Exploration with the Data #We examine the ABV and IBU for states that has 20 or more Ounces in their Beer they sell. We see from visualization that the ABV tends to be much higher since more Ounces are sold in the container. Maybe it is possible Budweiser can see more revenue growth in increasing their ounces in per which thus increasing their ABV..</p>
<p>#Recently Budweiser has been accused of watering down their beer due to shortages in alchol that they can provide. It is possible Budweiser could increase the Ounces and IBU in their alcohol to keep the level of 5% ABV in their beverage. As we can see with other beers that their ABV increases with the IBU.</p>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="Case-Study-01_files/figure-html/exploring-1.png" width="672" /></p>
<p>#Conclusion</p>
<p>#We were able to learn new information about Beers and Breweries in the United States including Alcohol by Volume and International Bitterness Units. Finding the average and median IBU and ABV we were able to discover a relationship between the two and showing that their is indeed a positive relationship with an increase in ABV there is an increaes in IBU. We were able to find information on how beer is consume in each region of the US and why more breweries are located in the West Coast and their bitterness they prefer compared to the East Cost of the US having less breweries and their IBU is lower than the west. We looked at what popular beer Budweiser creates and found that their ABV is around the median of other beers other companies put on. Their IBU is about average compared to other companies that create beers as well.</p>
<p>#If there is potential to tap into a new market by increasing ounces in their beer the ABV can surely be increased. If there is potential to move their product to the east cost, they could test the market on a new beer that has less IBU compared to what they sell now. #Information is provided to allow executives to make an important business decision on what they would like to do or potentially do. #</p>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
